### ISSUE TITLE
Adding new task cancels previews task adding

### ISSUE THREAD

**Issue by hoodie** [iamsergio/flow-pomodoro#1]
Hi, I read your blog article and decided to give it a try for the coming week.
I immediately found something I'd call at least buggish.

When you add a new task and then press the (+) Button before confirming the name, it adds the new-task, but resets the name to "New Task".

What I wanted to do, was add a bunch of tasks one after the other.

**Comment by iamsergio** [comment]
Are you building from source ? If yes I just fixed this, so update.

Thanks

**Comment by hoodie** [comment]
yes! works!!
Thank you!
