### ISSUE TITLE
User local hosts file

### ISSUE THREAD

**Issue by Dietr1ch** [iamsergio/flow-pomodoro#15]
Apparently it's possible to use a local hosts file like `~/.hosts` [See this](https://unix.stackexchange.com/questions/10438/can-i-create-a-user-specific-hosts-file-to-complement-etc-hosts)

It would be nice to be able to change it to avoid changing permissions on files managed by the package manager.

**Comment by iamsergio** [comment]
Does it work for you ? For example if you add "127.0.0.1 facebook.com", does it block it ?
Doesn't for me

**Comment by Dietr1ch** [comment]
I thought it was due to not updating `$HOSTALIASES`, but now I rebooted and it doesn't work =/

It seems it only works for certain hostname resolving paths, so it's not reliable. I'll close this.
