### ISSUE TITLE
Hardcoded libdir

### ISSUE THREAD

**Issue by mrueg** [iamsergio/flow-pomodoro#4]
In https://github.com/iamsergio/flow-pomodoro/blob/master/plugins/distractions/CMakeLists.txt#L14

On 64-bit systems you want to install it to lib64 instead.

**Comment by iamsergio** [comment]
I checked the Filesystem Hierarchy Standard and doesn't enforce that, in fact I checked archlinux and ubuntu and both have 64bit binaries in lib/

Maybe the best way is to have an optional argument passed to cmake so it's configurable

**Comment by mrueg** [comment]
I guess something like ${LIB_INSTALL_DIR} will work, too? See http://librelist.com/browser//yajl/2010/3/25/patch-install-into-usr-lib64-on-x86-64-arch-where-needed/

**Comment by iamsergio** [comment]
fixed with c1062dcdb03a9c3f9
