### ISSUE TITLE
Window location issue in Windows 8.1

### ISSUE THREAD

**Issue by flowlikeh2o** [iamsergio/flow-pomodoro#5]
I assume WM defined should allow me to move the window but unfortunately I am unable to drag the window at all. The preset options all invariably block something important, so while this is an amazing program the inability to move the window to a location that doesn't impede function is making it difficult to use right now.

Thanks.

**Comment by iamsergio** [comment]
WM defined means flow doesn't set a position, it's your WM that sets a position.
Windows doesn not allow you to move frameless-windows, it's a Windows specific behaviour.
Here's a workaround:

Choose "Last Position", in the combo-box.
Quit flow.
Open regedit
Go to HKEY_CURRENT_USER\Software\KDAB\flow-pomodoro
Edit windowLastPositionX and windowLastPositionY, and choose the position you want

**Comment by flowlikeh2o** [comment]
Thank you for the workaround. This works perfectly for now.

________________________________
